# Exercises

In [3]:
import numpy as np

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [6]:

# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]
height1 = np.array(height)
weight1 = np.array(weight)
result = (weight1 / (height1 ** 2)) * 730
print(result)



[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [21]:
def new_matrix(param1, param2, shape):
    arr_range = np.arange(param1, param2).reshape(shape)
    return arr_range

print(new_matrix(0,16, (4, 4)))

# """
# Example Result for make_matrix(0,15,(3,3)):
# array([[14.21633515,  7.98846653,  9.64140715],
#        [ 6.30982234,  9.96414331,  8.43153688],
#        [14.73102068, 11.76072894, 14.23356121]])
# """
# def make_matrix(low,high,shape,data_type = float): -- Example
#     pass

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### #3 - Open and load the data for the Chicago White Sox hitting data for this past season.Create a function that will compare the infield players output vs the outfield players output vs *hybrid. (Infield - {C, 1B, 2B, SS, 3B, MI}, Outfield - {LF, CF, RF, OF}, *Hybrid - {DH, UT}) for a specific stat. i.e. BA or HR or OPS

*Hybrid is optional


In [34]:
import csv
import numpy as np

#Test to make sure you have the correct data
def open_csv(filename, d=','):
    data = []
    with open(filename, encoding = 'utf-8')as mData:
        info = csv.reader(mData, delimiter = d)
        for row in info:
            data.append(row)
    return data
csv_data = open_csv('whitesox_2021_hitting.csv')


    


In [41]:
#3 - Open and load the data for the Chicago White Sox
# hitting data for this past season.Create a function
# that will compare the infield players output vs 
# the outfield players output vs *hybrid. 
# (Infield - {C, 1B, 2B, SS, 3B, MI}, Outfield - 
# {LF, CF, RF, OF}, *Hybrid - {DH, UT}) 
# for a specific stat. i.e. BA or HR or OPS

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
def load_data(filename, d=','):
    data = np.genfromtxt(filename, dtype=DATATYPES, delimiter=d,
                        filling_values='N/A', names=True, invalid_raise=False)
    return data

whitesox = load_data('whitesox_2021_hitting.csv')
all_players = whitesox['Name']
print(infield)
print(all_players)

# def find():
    
# print(find(stuff));



[b'Yasmani Grandal' b'Jos\xc3\xa9 Abreu' b'Cesar Hernandez'
 b'Tim Anderson' b'Yoan Moncada' b'Andrew Vaughn' b'Luis Robert'
 b'Adam Eaton' b'Yermin Mercedes' b'Leury Garcia' b'Brian Goodwin'
 b'Eloy Jimenez' b'Zack Collins' b'Nick Madrigal' b'Danny Mendick'
 b'Gavin Sheets' b'Adam Engel' b'Billy Hamilton' b'Jake Lamb'
 b'Seby Zavala' b'Jake Burger' b'Romy Gonzalez' b'Nick Williams'
 b'Luis Gonzalez']
[b'Yasmani Grandal' b'Jos\xc3\xa9 Abreu' b'Cesar Hernandez'
 b'Tim Anderson' b'Yoan Moncada' b'Andrew Vaughn' b'Luis Robert'
 b'Adam Eaton' b'Yermin Mercedes' b'Leury Garcia' b'Brian Goodwin'
 b'Eloy Jimenez' b'Zack Collins' b'Nick Madrigal' b'Danny Mendick'
 b'Gavin Sheets' b'Adam Engel' b'Billy Hamilton' b'Jake Lamb'
 b'Seby Zavala' b'Jake Burger' b'Romy Gonzalez' b'Nick Williams'
 b'Luis Gonzalez']
